### PR TITLE
Add 2 missing aliases for cfr template on cswiki

### PR DESCRIPTION
**Pull request by dvorapa**

### CODE REVIEW

**Comment by dvorapa** [comment]
@jack17529 I just moved it to the end, nothing is missing

**Comment by magul** [comment]
Hi @dvorapa , You have created pull reqeust only to semi-official mirror of pywikibot. If You want to merge your change, see: Developing pywikibot on https://www.mediawiki.org/wiki/Manual:Pywikibot

**Comment by dvorapa** [comment]
I see, but the tutorial here: https://www.mediawiki.org/wiki/Manual:Pywikibot/Development looks really complicated and I don't have got any time to go through all three parts of it. Maybe I'll ask somebody who has made this configuration before or I'll start a new task on Phabricator. I merged all these templates into one new and therefore I just want to add "přesunout" and "přejmenovat".

**Comment by magul** [comment]
Yes, I undestand, that it could looks really complicated, but after a while it's not :).

I just doubt that creating will make any change, almost nobody will see it here. :(

**Comment by dvorapa** [comment]
btw there is still an old bug in category.py with CFD templates on cswiki too https://phabricator.wikimedia.org/T135304. Combined with this issue bot can not handle CFR or CFD templates on cswiki at all when moving a category.

**Comment by magul** [comment]
I haven't review diff here at all, sorry. It's just much more effective to push this patch directly into gerrit.

**Comment by matejsuchanek** [comment]
Submitted as https://gerrit.wikimedia.org/r/#/c/354554/

**Comment by magul** [comment]
so maybe we should close it? @dvorapa ?

**Comment by dvorapa** [comment]
I asked Matěj Suchánek for help, we can close it I think

**Pull request closed without merging**
