### PR TITLE
Update weblinkchecker.py

### PR DESCRIPTION
**Pull request by zoranzoki21**
Can you change this, because now can not adding blank lines? Now adding only one lines, no like before three.

### CODE REVIEW

**Comment by magul** [comment]
Hi @zoranzoki21, first of all thank you for your pull request, but You should be aware, that only way to introduce change in official pywikibot repository is by official Wikimedia Fundation's Phabricator and Gerrit isntance.

See **develop pywikibot** section on https://www.mediawiki.org/wiki/Manual:Pywikibot

**Comment by zoranzoki21** [comment]
Okey

**Comment by magul** [comment]
So if You will introduce this change through Gerrit, could You, please, close this pull request?

**Comment by zoranzoki21** [comment]
Yes. Thank you!

2017-06-05 10:18 GMT+02:00 Tomasz Magulski <notifications@github.com>:

**Pull request closed without merging**
